version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mypass123
      MYSQL_DATABASE: transaction
      MYSQL_USER: sena
      MYSQL_PASSWORD: mypass123

  srcConsumer:
    build: ./srcConsumer
    ports:
      - "3000:3000"
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_QUEUE: queue2
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: mypass123
      MYSQL_DATABASE: transaction

  srcProducer:
    build: ./srcProducer
    ports:
      - "4000:4000"
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_QUEUE: queue2
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: mypass123
      MYSQL_DATABASE: transaction
